# Generated by Django 5.2 on 2025-06-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'FAQ Comment', 'verbose_name_plural': 'FAQ Comments'},
        ),
        migrations.AddField(
            model_name='faqcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='faqcomment',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='faqcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Posted at'),
        ),
    ]
