# Generated by Django 5.2 on 2025-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_faqcomment_options_faqcomment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcomment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this comment should be shown publicly', verbose_name='Is Active'),
        ),
    ]
