# Generated by Django 5.2 on 2025-07-26 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_rangelocation_trainingpackage_weapon_instructor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_available', models.BooleanField(default=False, verbose_name='Is Available')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='lessons.rangelocation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_completed',
            field=models.BooleanField(default=False, verbose_name='Payment Completed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='end_time',
            field=models.TimeField(default='17:00', verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='start_time',
            field=models.TimeField(default='09:00', verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='lessons.instructor', verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='lessons.weapon'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='available_days',
            field=models.CharField(help_text='Comma-separated list of available weekdays (0-6)', max_length=100, verbose_name='Available Days'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date'], name='lessons_boo_date_5f92a2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='lessons_boo_status_8844ce_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='lessons_boo_payment_a3e4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='lessons_boo_user_id_caf370_idx'),
        ),
        migrations.AddIndex(
            model_name='faqcomment',
            index=models.Index(fields=['is_active'], name='lessons_faq_is_acti_7b26dc_idx'),
        ),
        migrations.AddIndex(
            model_name='faqcomment',
            index=models.Index(fields=['created_at'], name='lessons_faq_created_db1c19_idx'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['is_active'], name='lessons_ins_is_acti_0bc738_idx'),
        ),
        migrations.AddIndex(
            model_name='rangelocation',
            index=models.Index(fields=['is_active'], name='lessons_ran_is_acti_04a1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_approved'], name='lessons_tes_is_appr_3e7cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['rating'], name='lessons_tes_rating_f3fed5_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingpackage',
            index=models.Index(fields=['is_active'], name='lessons_tra_is_acti_985b91_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingpackage',
            index=models.Index(fields=['price'], name='lessons_tra_price_5d11da_idx'),
        ),
        migrations.AddIndex(
            model_name='weapon',
            index=models.Index(fields=['type'], name='lessons_wea_type_38825d_idx'),
        ),
        migrations.AddIndex(
            model_name='weapon',
            index=models.Index(fields=['is_active'], name='lessons_wea_is_acti_79dd1b_idx'),
        ),
        migrations.AddField(
            model_name='availability',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='lessons.instructor'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['date'], name='lessons_ava_date_92a926_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['is_available'], name='lessons_ava_is_avai_9af429_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('instructor', 'date')},
        ),
    ]
