# Generated by Django 5.2 on 2025-07-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_availability_remove_booking_email_and_more'),
    ]

    operations = [
    ]
