# Generated by Django 5.2 on 2025-07-26 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_populate_instructor_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='lessons.instructor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('cash', 'Cash')], default='paypal', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='available_days',
            field=models.CharField(default='0,1,2,3,4', help_text='Comma-separated list of available weekdays (0-6)', max_length=100, verbose_name='Available Days'),
        ),
    ]
