# Generated by Django 5.2 on 2025-07-26 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_booking_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Start Time'),
        ),
    ]
