# Generated by Django 5.2 on 2025-07-27 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_instructor_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100, verbose_name='Transaction ID')),
                ('payment_status', models.CharField(max_length=20, verbose_name='Payment Status')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Payment Amount')),
                ('payer_email', models.EmailField(max_length=254, verbose_name='Payer Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PayPal Transaction',
                'verbose_name_plural': 'PayPal Transactions',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='paypal_txn_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='PayPal Transaction ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('cash', 'Cash'), ('credit_card', 'Credit Card')], default='paypal', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['paypal_txn_id'], name='lessons_boo_paypal__3ca39f_idx'),
        ),
        migrations.AddField(
            model_name='paypaltransaction',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_transactions', to='lessons.booking'),
        ),
        migrations.AddIndex(
            model_name='paypaltransaction',
            index=models.Index(fields=['txn_id'], name='lessons_pay_txn_id_1d2748_idx'),
        ),
        migrations.AddIndex(
            model_name='paypaltransaction',
            index=models.Index(fields=['payment_status'], name='lessons_pay_payment_ce2b37_idx'),
        ),
    ]
